package uk.ac.soton.mib104.t2.activities.json;

import java.util.Map;

/**
 * An object that creates and merges templates.  
 * 
 * @author Mark Borkum
 * @version 0.0.1-SNAPSHOT
 *
 * @param <T>  the type of templates used/generated by this service
 * @param <V>  the type of values generated by this service
 */
public interface TemplateService<T, V> {

	/**
	 * Creates a new template using the given string <code>t</code>. 
	 * 
	 * @param t
	 * @return
	 * @throws Throwable
	 */
	public T createTemplate(String t) throws Throwable;
	
	/**
	 * Merges the template representation of the given string <code>t</code> with the
	 * given <code>bindings</code>, and returns the final representation of the result. 
	 * <p>
	 * Equivalent to: <code>this.mergeTemplate(this.createTemplate(t), bindings);</code>
	 * 
	 * @param t
	 * @param bindings
	 * @return
	 * @throws Throwable
	 */
	public V mergeTemplate(String t, Map<String, Object> bindings) throws Throwable;
	
	/**
	 * Merges the given <code>template</code> and <code>bindings</code> and returns the 
	 * final representation of the result. 
	 * 
	 * @param template
	 * @param bindings
	 * @return 
	 * @throws Throwable
	 */
	public V mergeTemplate(T template, Map<String, Object> bindings) throws Throwable;
	
}
